
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VeloTours.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Comment
{

    public int CommentID { get; set; }

    public string ParentCommentID { get; set; }

    public string Text { get; set; }

    public System.DateTime Created { get; set; }



    public virtual Athlete Athlete { get; set; }

}

}
