
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VeloTours.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Effort
{

    public Effort()
    {

        this.LeaderBoard = new HashSet<LeaderBoard>();

    }


    public int EffortID { get; set; }

    public int AthleteID { get; set; }

    public string StravaActivityID { get; set; }

    public string StravaID { get; set; }

    public System.DateTime StartDate { get; set; }

    public Nullable<System.TimeSpan> ElapsedTime { get; set; }

    public Nullable<int> VAM { get; set; }



    public virtual Athlete Athlete { get; set; }

    public virtual ICollection<LeaderBoard> LeaderBoard { get; set; }

}

}
