//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeloTours.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Effort
    {
        public int EffortID { get; set; }
        public int ResultID { get; set; }
        public int AthleteID { get; set; }
        public int StravaActivityID { get; set; }
        public int StravaID { get; set; }
        public System.DateTime StartDate { get; set; }
        public int ElapsedTime { get; set; }
        public Nullable<int> VAM { get; set; }
    
        public virtual Result Result { get; set; }
        public virtual Athlete Athlete { get; set; }
    }
}
