
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VeloTours.Models
{

using System;
    
public partial class ElapsedTimes
{

    public int Min { get; set; }

    public int Median { get; set; }

    public int Average { get; set; }

    public int Max { get; set; }

    public double Stdev { get; set; }

    public int Percentile90 { get; set; }

}

}
