
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VeloTours.Models
{

using System;
    
public partial class ElapsedTimes
{

    public Nullable<int> Min { get; set; }

    public Nullable<int> Median { get; set; }

    public Nullable<int> Average { get; set; }

    public Nullable<int> Max { get; set; }

    public Nullable<double> Stdev { get; set; }

    public Nullable<int> Percentile90 { get; set; }

}

}
