//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeloTours.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public Grade()
        {
            this.SegmentInfo = new HashSet<SegmentInfo>();
        }
    
        public int GradeID { get; set; }
        public int Climb { get; set; }
        public int Sprint { get; set; }
    
        public virtual ICollection<SegmentInfo> SegmentInfo { get; set; }
    }
}
