
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VeloTours.Models
{

using System;
    using System.Collections.Generic;
    
public partial class LeadershipBoard
{

    public int LeaderBoardID { get; set; }

    public int ResultPeriodID { get; set; }

    public int AthleteID { get; set; }

    public int Rank { get; set; }

    public System.TimeSpan Duration { get; set; }

    public Nullable<int> YellowPoints { get; set; }

    public int GreenPoints { get; set; }

    public int PolkaDotPoints { get; set; }

    public int NoSegmentsRidden { get; set; }

    public Nullable<int> VAM { get; set; }



    public virtual Athlete Athlete { get; set; }

    public virtual ResultPeriod ResultPeriods { get; set; }

}

}
