
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VeloTours.Models
{

using System;
    using System.Collections.Generic;
    
public partial class LeadershipBoard
{

    public int LeaderBoardID { get; set; }

    public int ResultPeriodID { get; set; }

    public int AthleteID { get; set; }

    public string Rank { get; set; }

    public string Duration { get; set; }

    public string GreenPoints { get; set; }

    public string PolkaDotPoints { get; set; }

    public string NoSegmentsRidden { get; set; }



    public virtual Athlete Athlete { get; set; }

    public virtual ResultPeriod ResultPeriods { get; set; }

}

}
