
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VeloTours.Models
{

using System;
    using System.Collections.Generic;
    
public partial class LeaderBoard
{

    public LeaderBoard()
    {

        this.ElapsedTimes = new ElapsedTimes();

    }


    public int LeaderBoardID { get; set; }

    public int ResultID { get; set; }

    public int AthleteID { get; set; }

    public int Rank { get; set; }

    public int YellowPoints { get; set; }

    public int GreenPoints { get; set; }

    public int PolkaDotPoints { get; set; }

    public int NoRidden { get; set; }



    public ElapsedTimes ElapsedTimes { get; set; }



    public virtual Result Result { get; set; }

    public virtual Athlete Athlete { get; set; }

}

}
