//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeloTours.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultPeriod
    {
        public ResultPeriod()
        {
            this.Statistic = new HashSet<Statistic>();
            this.LeaderBoard = new HashSet<LeaderBoard>();
        }
    
        public int ResultPeriodID { get; set; }
        public Nullable<int> SegmentID { get; set; }
        public Nullable<int> SegmentAreaID { get; set; }
        public string Name { get; set; }
        public System.DateTime From { get; set; }
        public System.DateTime To { get; set; }
    
        public virtual ICollection<Statistic> Statistic { get; set; }
        public virtual ICollection<LeaderBoard> LeaderBoard { get; set; }
        public virtual Segment Segment { get; set; }
        public virtual SegmentArea SegmentArea { get; set; }
    }
}
