
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VeloTours.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ResultPeriod
{

    public ResultPeriod()
    {

        this.LeadershipBoards = new HashSet<LeadershipBoard>();

        this.Statistics = new HashSet<Statistic>();

    }


    public int ResultPeriodID { get; set; }

    public string Name { get; set; }

    public System.DateTime From { get; set; }

    public System.DateTime To { get; set; }



    public virtual ICollection<LeadershipBoard> LeadershipBoards { get; set; }

    public virtual ICollection<Statistic> Statistics { get; set; }

    public virtual Segment Segment { get; set; }

}

}
