//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeloTours.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Segment
    {
        public Segment()
        {
            this.SegmentAreas = new HashSet<SegmentArea>();
            this.Info = new Statistics();
        }
    
        public int SegmentID { get; set; }
    
        public Statistics Info { get; set; }
    
        public virtual ICollection<SegmentArea> SegmentAreas { get; set; }
        public virtual Result Result { get; set; }
    }
}
