//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeloTours.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Segment
    {
        public int SegmentID { get; set; }
        public string Name { get; set; }
        public int StravaID { get; set; }
        public int SegmentAreaID { get; set; }
    
        public virtual SegmentArea SegmentArea { get; set; }
        public virtual SegmentInfo SegmentInfo { get; set; }
    }
}
