//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeloTours.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegmentInfo
    {
        public SegmentInfo()
        {
            this.Statistic = new HashSet<Statistic>();
        }
    
        public int SegmentInfoID { get; set; }
        public Nullable<double> Distance { get; set; }
        public Nullable<int> ElevDifference { get; set; }
        public Nullable<double> AvgGrade { get; set; }
        public Nullable<int> Riders { get; set; }
        public Nullable<int> Ridden { get; set; }
        public int GradeGradeID { get; set; }
    
        public virtual SegmentArea SegmentArea { get; set; }
        public virtual ICollection<Statistic> Statistic { get; set; }
        public virtual Grade Grade { get; set; }
    }
}
