//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeloTours.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegmentArea
    {
        public SegmentArea()
        {
            this.Segment = new HashSet<Segment>();
            this.ResultPeriod = new HashSet<ResultPeriod>();
        }
    
        public int SegmentAreaID { get; set; }
        public int RegionID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Distance { get; set; }
        public Nullable<int> ElevDifference { get; set; }
        public Nullable<double> AvgGrade { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual ICollection<Segment> Segment { get; set; }
        public virtual ICollection<ResultPeriod> ResultPeriod { get; set; }
    }
}
