//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeloTours.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegmentArea
    {
        public SegmentArea()
        {
            this.Segments = new HashSet<Segment>();
            this.Info = new Statistics();
        }
    
        public int SegmentAreaID { get; set; }
        public int RegionID { get; set; }
        public Nullable<System.Guid> SecretKey { get; set; }
    
        public Statistics Info { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual ICollection<Segment> Segments { get; set; }
        public virtual Result Result { get; set; }
    }
}
