//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeloTours.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic
    {
        public int StatisticID { get; set; }
        public string Period { get; set; }
        public string YerseyType { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public int Points { get; set; }
        public int SegmentSegmentID { get; set; }
        public int SegmentInfoSegmentInfoID { get; set; }
    
        public virtual Athlete Athlete { get; set; }
        public virtual SegmentInfo SegmentInfo { get; set; }
    }
}
