

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VeloTours.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class TourModelContainer : DbContext
{
    public TourModelContainer()
        : base("name=TourModelContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Athlete> Athletes { get; set; }

    public DbSet<Country> Countries { get; set; }

    public DbSet<LeadershipBoard> LeadershipBoards { get; set; }

    public DbSet<Region> Regions { get; set; }

    public DbSet<ResultPeriod> ResultPeriods { get; set; }

    public DbSet<SegmentArea> SegmentAreas { get; set; }

    public DbSet<Segment> Segments { get; set; }

    public DbSet<Statistic> Statistics { get; set; }

    public DbSet<Comment> Comments { get; set; }

}

}

